# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Diffing' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'SnapKit', '~> 4.0.0'
  pod 'CHTCollectionViewWaterfallLayout/Swift'
  pod 'IGListKit', '~> 3.0'

end
